import os

from dotenv import load_dotenv


load_dotenv()

NEO4J_URI = "bolt://localhost:7687"
NEO4J_AUTH = ("neo4j", "koi-pond")
NEO4J_DB = "neo4j" 

CACHE_DIRECTORY = "cache"

OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]

PINECONE_API_KEY = os.environ["PINECONE_API_KEY"]
PINECONE_CLOUD_PROVIDER = "aws"
PINECONE_CLOUD_REGION = "us-east-1"
PINECONE_INDEX_METRIC = "cosine"
PINECONE_INDEX_NAME = "koi-pond"
PINECONE_BATCH_SIZE = 64
EMBEDDINGS_DIMENSION = 1024

VOYAGEAI_API_KEY = os.environ["VOYAGE_API_KEY"]
VOYAGEAI_MODEL = "voyage-2"
VOYAGEAI_BATCH_SIZE = 128

MAX_CHUNK_SIZE = 512
CHUNK_OVERLAP = 80

PUBPUB_USERNAME = os.environ["PUBPUB_USERNAME"]
PUBPUB_PASSWORD = os.environ["PUBPUB_PASSWORD"]